#!/usr/bin/env python3
"""
Build the population-reference table for UP Health Design (SPEC-Health-Design §3.4).

Source: NHANES 2017–March 2020 pre-pandemic public-use files (CDC/NCHS, public domain).
Output: lib/health-design/reference/nhanes-2017-2020.json — survey-weighted percentiles
per metric × sex × age band for adults ≥20. Aggregates only; no microdata is stored.

Usage:  python3 scripts/build-reference.py <dir-with-P_*.xpt>
Needs:  pip3 install pyreadstat numpy
"""
import json, sys, os, datetime
import numpy as np, pyreadstat

D = sys.argv[1] if len(sys.argv) > 1 else "."
OUT = os.path.join(os.path.dirname(__file__), "..", "lib/health-design/reference/nhanes-2017-2020.json")
PCTS = [5, 10, 25, 50, 75, 90, 95]
BANDS = [("20-39", 20, 39), ("40-59", 40, 59), ("60+", 60, 200)]

def load(name):
    df, _ = pyreadstat.read_xport(os.path.join(D, f"{name}.xpt")); return df

demo = load("P_DEMO")[["SEQN", "RIDAGEYR", "RIAGENDR", "WTMECPRP"]]
files = {
    "P_GHB":   {"hba1c": ("LBXGH", "%", "WTMECPRP")},
    "P_GLU":   {"fbs": ("LBXGLU", "mg/dL", "WTSAFPRP")},
    "P_TCHOL": {"cholesterol": ("LBXTC", "mg/dL", "WTMECPRP")},
    "P_HDL":   {"hdl": ("LBDHDD", "mg/dL", "WTMECPRP")},
    "P_TRIGLY":{"triglyceride": ("LBXTR", "mg/dL", "WTSAFPRP"), "ldl": ("LBDLDL", "mg/dL", "WTSAFPRP")},
    "P_BIOPRO":{"alt_sgpt": ("LBXSATSI", "U/L", "WTMECPRP"), "ast_sgot": ("LBXSASSI", "U/L", "WTMECPRP"),
                "creatinine": ("LBXSCR", "mg/dL", "WTMECPRP"), "uric_acid": ("LBXSUA", "mg/dL", "WTMECPRP"),
                "albumin": ("LBXSAL", "g/dL", "WTMECPRP"), "alp": ("LBXSAPSI", "U/L", "WTMECPRP")},
    "P_HSCRP": {"hs_crp": ("LBXHSCRP", "mg/L", "WTMECPRP")},
    "P_BMX":   {"bmi": ("BMXBMI", "kg/m²", "WTMECPRP"), "waist": ("BMXWAIST", "cm", "WTMECPRP")},
}

def wpct(values, weights, pcts):
    o = np.argsort(values); v, w = values[o], weights[o]
    cw = np.cumsum(w); cw = cw / cw[-1]
    return [float(np.round(np.interp(p / 100, cw, v), 2)) for p in pcts]

out = {"source": "NHANES 2017–March 2020 pre-pandemic (CDC/NCHS) · adults ≥20 · survey-weighted",
       "built_at": datetime.date.today().isoformat(), "percentiles": PCTS, "note": "ประชากรสหรัฐ — ใช้บอกตำแหน่งเทียบคนวัยเดียวกันเท่านั้น ไม่ใช่เกณฑ์สุขภาพ · เปลี่ยนเป็น Thai NHES เมื่อได้ข้อมูล",
       "metrics": {}}
for fname, cols in files.items():
    df = load(fname)
    for key, (col, unit, wcol) in cols.items():
        w = df[["SEQN", col] + ([wcol] if wcol in df.columns else [])]
        m = demo.merge(w, on="SEQN")
        wname = wcol if wcol in m.columns else "WTMECPRP"
        m = m[(m.RIDAGEYR >= 20) & m[col].notna() & (m[wname] > 0)]
        cell = {}
        for sex, code in (("male", 1), ("female", 2)):
            for band, lo, hi in BANDS:
                s = m[(m.RIAGENDR == code) & (m.RIDAGEYR >= lo) & (m.RIDAGEYR <= hi)]
                if len(s) < 100: continue
                cell[f"{sex}:{band}"] = {"n": int(len(s)), "p": wpct(s[col].to_numpy(float), s[wname].to_numpy(float), PCTS)}
        out["metrics"][key] = {"unit": unit, "weight": wname, "cells": cell}
        print(f"{key:12} {unit:6} cells={len(cell)} n={sum(c['n'] for c in cell.values())}")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
json.dump(out, open(OUT, "w"), ensure_ascii=False, indent=1)
# A .ts twin so both Next and node:test import it without JSON import attributes.
TS = OUT[:-5] + ".ts"
with open(TS, "w") as f:
    f.write("// GENERATED by scripts/build-reference.py — do not edit. Same content as the .json next to it.\n")
    f.write("const table = " + json.dumps(out, ensure_ascii=False, indent=1) + " as const;\nexport default table;\n")
print("wrote", os.path.abspath(OUT), "and", os.path.abspath(TS))
