import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth/session";
import { isAssignedToCustomer, isDownlineCustomer } from "@/lib/customers/access";
import { createAdminClient } from "@/lib/supabase/admin";
import { getReportHtml, saveReportHtml } from "@/lib/reports/report-store";

export const dynamic = "force-dynamic";

/**
 * Serve a customer's Medication & Supplement Map (interactive HTML) behind auth.
 *
 * Mirrors the lab-report route. The per-customer report is generated by the coach
 * (via Claude Code / cowork) and uploaded (PUT) into the PRIVATE Supabase store
 * (customer_report_html, kind='med_map'). It contains sensitive clinical data
 * (psychiatric meds, allergies), so it is NEVER committed to the (public) git repo
 * or placed in /public, and is returned only to the owning coach (or admin) after a
 * session + ownership check. Unlike lab-report there is no public share link.
 */
export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const session = await getSession();
  if (!session) return new NextResponse("unauthorized", { status: 401 });

  // id must be a plain UUID before it touches the DB
  if (!/^[0-9a-fA-F-]{36}$/.test(params.id)) {
    return new NextResponse("bad id", { status: 400 });
  }

  const admin = createAdminClient();
  const { data: customer } = await admin
    .from("customers").select("id, coach_id").eq("id", params.id).maybeSingle();
  if (!customer) return new NextResponse("customer not found", { status: 404 });

  const isAdmin = session.profile.role === "admin";
  if (
    !isAdmin &&
    customer.coach_id !== session.user.id &&
    !(await isAssignedToCustomer(session.user.id, params.id)) &&
    !(await isDownlineCustomer(session.user.id, params.id))
  ) {
    return new NextResponse("forbidden", { status: 403 });
  }

  const html = await getReportHtml(params.id, "med_map");
  if (!html) {
    return new NextResponse("ยังไม่มีรายงานแผนผังยาสำหรับลูกค้ารายนี้", { status: 404 });
  }
  return new NextResponse(html, {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "private, no-store",
    },
  });
}

/**
 * Upload / replace a customer's Med-Map HTML (coach or admin).
 * Body = raw HTML. Stored gzip+base64 in Supabase (never git/public). Ensures a
 * med_map record exists so the customer's "แผนผังยา & อาหารเสริม" button appears
 * (the 360 route's `hasMedMap` flag keys off it). No share token — med-map has no
 * public link, unlike lab-report.
 */
export async function PUT(req: Request, { params }: { params: { id: string } }) {
  const session = await getSession();
  if (!session) return new NextResponse("unauthorized", { status: 401 });
  if (!/^[0-9a-fA-F-]{36}$/.test(params.id)) return new NextResponse("bad id", { status: 400 });

  const admin = createAdminClient();
  const { data: customer } = await admin
    .from("customers").select("id, coach_id").eq("id", params.id).maybeSingle();
  if (!customer) return new NextResponse("customer not found", { status: 404 });

  const isAdmin = session.profile.role === "admin";
  // write access = admin / owner / co-coach (NOT downline — that's read-only)
  if (!isAdmin && customer.coach_id !== session.user.id && !(await isAssignedToCustomer(session.user.id, params.id))) {
    return new NextResponse("forbidden", { status: 403 });
  }

  const html = await req.text();
  if (!html || html.length < 200 || !/<!doctype html|<html/i.test(html)) {
    return NextResponse.json({ error: "ไฟล์ที่อัปโหลดไม่ใช่ HTML report ที่ถูกต้อง" }, { status: 400 });
  }

  await saveReportHtml(params.id, html, "med_map");

  // ensure a med_map record exists so `hasMedMap` (360 route) turns the view button on
  const { data: rec } = await admin
    .from("customer_records")
    .select("id")
    .eq("customer_id", params.id).eq("document_type", "med_map").maybeSingle();
  if (!rec) {
    await admin.from("customer_records").insert({
      customer_id: params.id, document_type: "med_map",
      recorded_at: new Date().toISOString().slice(0, 10), source: "Med-Map",
      created_by: session.user.id,
    });
  }

  return NextResponse.json({ ok: true, bytes: html.length });
}
